### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by NNK-KALI** [zxllkada/Get-instagram-users-info---Any-instagram-account#12]
![Screenshot_20210106_174158](https://user-images.githubusercontent.com/63394300/103767380-82f59f00-5046-11eb-8af3-b0db3afb908f.jpg)

**Comment by NNK-KALI** [comment]
I fixed it with
```pip install igql```

**Comment by NNK-KALI** [comment]
Please mention that above command in installation process.

**Comment by zxllkada** [comment]
> Please mention that above command in installation process.

Thank you.
