### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by farman00** [zxllkada/Get-instagram-users-info---Any-instagram-account#13]
When I search username then he show me Not on instagram

**Comment by zxllkada** [comment]
Hello @farman00 

Its true i will fix it soon.

The problem i set only one user-agent so all users using the same user-agent as a result instagram blocked us all.

Keep your eyes on my telegram channel t.me/zxllkada

**Comment by zxllkada** [comment]
Hello @farman00

Its true i will fix it soon.

The problem i set only one user-agent so all users using the same user-agent as a result instagram blocked us all.

Keep your eyes on my telegram channel [LinkToMyChannel](https://t.me/zxllkada)

**Comment by zxllkada** [comment]
> When I search username then he show me Not on instagram

Hello update it now. I hope it fixed.

**Comment by TheBorinator** [comment]
It is not fixed

**Comment by zxllkada** [comment]
> It is not fixed

" it is not fixed " i cannot help you with this word. Send to me "Output" or screenshot.

**Comment by zxllkada** [comment]
[ ! ] Change your IP first .
