### ISSUE TITLE
Don't want work

### ISSUE THREAD

**Issue by BDW87** [zxllkada/Get-instagram-users-info---Any-instagram-account#17]
I tested it with private and open profiles, with and without VPN and changed MAC's it respond everytime
time the same result:

NOT ON INSTAGRAM OR TOO MANY REQUESTS

, why you don't changed the code that's the user can log into there accounts like Osintgram or others ?
Maybe it will fix it ..

Gretes

**Comment by zxllkada** [comment]
Its working just try again, make sure you installed all new lib. Check them out.

**Comment by BDW87** [comment]
<img width="1024" alt="Bildschirmfoto 2021-03-19 um 23 21 46" src="https://user-images.githubusercontent.com/14155187/111848254-ef283500-890a-11eb-8584-83f5bd4f6085.png">
urllib.request doesn't exist ..

**Comment by zxllkada** [comment]
Its okey just keep

**Comment by BDW87** [comment]
i don't want be disrespectful but tell me why you don't want to helping me fixing my Issues what's your Problem??

**Comment by zxllkada** [comment]
urllib.request its inside urllib3 LIB, that's why I said its okay. If pip3 install urllib3 not working use pip install urllib.request it will be fixed.
