### ISSUE TITLE
It is not working and it shows like this 

### ISSUE THREAD

**Issue by royalsaithilak** [zxllkada/Get-instagram-users-info---Any-instagram-account#20]
![Screenshot_20210413_090718](https://user-images.githubusercontent.com/50959649/114493290-ebe94600-9c37-11eb-8afa-4d2da0b39d27.jpg)

See last arrow marked one

![IMG_20210413_091026](https://user-images.githubusercontent.com/50959649/114493416-28b53d00-9c38-11eb-8114-eecab9410149.jpg)
Say me how to fix this

**Comment by Progluver** [comment]
These are case sensitive. So it must be `python3 InstaInfo_zxll.py`  instead of `python3 instaInfo_zxll.py` where **'I'** of **InstaInfo_zxll.py** is in upper case. 

@royalsaithilak

**Comment by royalsaithilak** [comment]
Tqsm BRO it's working now
