### ISSUE TITLE
Not working!!!

### ISSUE THREAD

**Issue by Mobly-0** [zxllkada/Get-instagram-users-info---Any-instagram-account#22]
Your Program returns the following error
"Not On instagram Or Too many Requests"
The account is there, How Do I Resolve this?

**Comment by zxllkada** [comment]
Go to google type : what is my useragent

Copy your useragent then.
Open PersonalLib folder then > Shadow.py file > go to line 58 then change useragent with your UserAgent.

Now save it. And open the tool again it will work.

**Comment by hamaz562006** [comment]
> Go to google type : what is my useragent
> 
> Copy your useragent then.
> Open PersonalLib folder then > Shadow.py file > go to line 58 then change useragent with your UserAgent.
> 
> Now save it. And open the tool again it will work.

don't work , return error "Not On instagram Or Too many Requests"

**Comment by zxllkada** [comment]
> > Go to google type : what is my useragent
> > Copy your useragent then.
> > Open PersonalLib folder then > Shadow.py file > go to line 58 then change useragent with your UserAgent.
> > Now save it. And open the tool again it will work.
> 
> don't work , return error "Not On instagram Or Too many Requests"

First install all Libs then change your user agent if it does not work change your IP and make sure username on Instagram

**Comment by hamaz562006** [comment]
> > > Go to google type : what is my useragent
> > > Copy your useragent then.
> > > Open PersonalLib folder then > Shadow.py file > go to line 58 then change useragent with your UserAgent.
> > > Now save it. And open the tool again it will work.
> > 
> > 
> > don't work , return error "Not On instagram Or Too many Requests"
> 
> First install all Libs then change your user agent if it does not work change your IP and make sure username on Instagram

I did everything you said, unfortunately it did not work for me

**Comment by Andres6174** [comment]
> Your Program returns the following error
> "Not On instagram Or Too many Requests"
> The account is there, How Do I Resolve this?

Same problem

**Comment by Andres6174** [comment]
Same problem

**Comment by zxllkada** [comment]
**Fixed. Try new version** ❤️
