### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by DJDarkCyber** [zxllkada/Get-instagram-users-info---Any-instagram-account#25]
Zxll / USERNAME > Zxll
 Zxll  NOT ON INSTAGRAM OR TOO MANY REQUESTS

I tried many entering many users/popular users, It still showing this like

**Comment by zxllkada** [comment]
Try real users only. 

if still not working try to change your IP Address.

**Comment by DJDarkCyber** [comment]
![image](https://user-images.githubusercontent.com/86729101/124222163-38258300-dacf-11eb-96dd-f8b91bd1a3b4.png)

See, Still not working

**Comment by ritikkesarwani5** [comment]
It's not working fake only

**Comment by zxllkada** [comment]
**Fixed. Try new version** ❤️
