### ISSUE TITLE
IP Block

### ISSUE THREAD

**Issue by AlyJa-091521** [zxllkada/Get-instagram-users-info---Any-instagram-account#38]
MAKING NEW COOKIES ] : SUPER_MODE/SuperLIB/cookie/cookies.txt
[ ClientError ] : Bad Request: ip_block
[ Code ] : 400
[ Response ] : {"message":"The username you entered doesn't appear to belong to an account. Please check your username and try again.","status":"fail","error_type":"ip_bl

**Comment by zxllkada** [comment]
Instagram blocked your IP ADRRESS
