### ISSUE TITLE
Not Giving Email and phone number of all profiles

### ISSUE THREAD

**Issue by Khattak24** [zxllkada/Get-instagram-users-info---Any-instagram-account#8]
Hello sir,
I run this script but i am not getting any any email and phone number. so Can you please help me out to get phone number and email also.
Thanks and Regards

**Comment by zxllkada** [comment]
It can be know right now.

**Comment by 123456789ankit** [comment]
It still not giving any email or phone number

Please do something

**Comment by zxllkada** [comment]
_**Because this information depends on user settings and instagram, make sure this information are available for this user**_
