### ISSUE TITLE
It accept the name but is not working.

### ISSUE THREAD

**Issue by rsa408** [zxllkada/Get-instagram-users-info---Any-instagram-account#9]
Hi,
I want to collect information of my follower's  I thought this tool will work for me but I didn't reach that stage accepts username but swearing that something is going wrong. I tried to contact you by telegram but that was your channel.

I am not a python programmer :(.

Regards

**Comment by zxllkada** [comment]
its not working now wait updates soon join my telegram channel for news.

**Comment by anoms-221** [comment]
link for your telegramme groupe
